# TODO: Set-up NuGet for releases.

name: Senko.Discord

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@1
  inputs:
    version: '3.1.201'
  displayName: install .NET Core 3

- script: dotnet restore
  displayName: dotnet restore

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: dotnet build

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true

- script: dotnet pack --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))
  displayName: pack

- task: NuGetCommand@2
  displayName: publish
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'MyGet'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'